# T81-558: Applications of Deep Neural Networks
**Class 2: Introduction to TensorFlow.**
* Instructor: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), School of Engineering and Applied Science, [Washington University in St. Louis](https://engineering.wustl.edu/Programs/Pages/default.aspx)
* For more information visit the [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

## Neural Network Basics

Neural networks were one of the first machine learning models.  Their popularity has fallen twice and is now on its third rise.  Deep learning implies the use of neural networks.  The "deep" in deep learning refers to a neural network with many hidden layers.  Because neural networks have been around for so long, they have quite a bit of baggage.  Many different training algorithms, activation/transfer functions, and structures have been added over the years.  This course is only concerned with the latest, most current state of the art techniques for deep neural networks.  I am not going to spend any time discussing the history of neural networks.  If you would like to learn about some of the more classic structures of neural networks, there are several chapters dedicated to this in your course book.  For the latest technology, I wrote an article for the Society of Actuaries on deep learning as the [third generation of neural networks](https://www.soa.org/Library/Newsletters/Predictive-Analytics-and-Futurism/2015/december/paf-iss12.pdf).

Neural networks accept input and produce output.  The input to a neural network is called the feature vector.  The size of this vector is always a fixed length.  Changing the size of the feature vector means recreating the entire neural network.  Though the feature vector is called a "vector," this is not always the case.  A vector implies a 1D array.  Historically the input to a neural network was always 1D.  However, with modern neural networks you might see inputs, such as:

* **1D Vector** - Classic input to a neural network, similar to rows in a spreadsheet.  Common in predictive modeling.
* **2D Matrix** - Grayscale image input to a convolutional neural network (CNN).
* **3D Matrix** - Color image input to a convolutional neural network (CNN).
* **nD Matrix** - Higher order input to a CNN.

Prior to CNN's, the image input was sent to a neural network simply by squashing the image matrix into a long array by placing the image's rows side-by-side.  CNNs are different, as the nD matrix literally passes through the neural network layers.

Initially this course will focus upon 1D input to neural networks.  However, later sessions will focus more heavily upon higher dimension input.

**Dimensions** The term dimension can be confusing in neural networks.  In the sense of a 1D input vector, dimension refers to how many elements are in that 1D array.  For example a neural network with 10 input neurons has 10 dimensions.  However, now that we have CNN's, the input has dimensions too.  The input to the neural network will *usually* have 1, 2 or 3 dimensions.  4 or more dimensions is unusual.  You might have a 2D input to a neural network that has 64x64 pixels.  This would result in 4,096 input neurons.  This network is either 2D or 4,096D, depending on which set of dimensions you are talking about!

# Classification or Regression

Like many models, neural networks can function in classification or regression:

* **Regression** - You expect a number as your neural network's prediction.
* **Classification** - You expect a class/category as your neural network's prediction.

The following shows a classification and regression neural network:

![Neural Network Classification and Regression](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_ann_class_reg.png "Neural Network Classification and Regression")

Notice that the output of the regression neural network is numeric and the output of the classification is a class.  Regression, or two-class classification, networks always have a single output.  Classification neural networks have an output neuron for each class. 

The following diagram shows a typical neural network:

![Feedforward Neural Networks](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_ann.png "Feedforward Neural Networks")

There are usually four types of neurons in a neural network:

* **Input Neurons** - Each input neuron is mapped to one element in the feature vector.
* **Hidden Neurons** - Hidden neurons allow the neural network to abstract and process the input into the output.
* **Output Neurons** - Each output neuron calculates one part of the output.
* **Context Neurons** - Holds state between calls to the neural network to predict.
* **Bias Neurons** - Work similar to the y-intercept of a linear equation.  

These neurons are grouped into layers:

* **Input Layer** - The input layer accepts feature vectors from the dataset.  Input layers usually have a bias neuron.
* **Output Layer** - The output from the neural network.  The output layer does not have a bias neuron.
* **Hidden Layers** - Layers that occur between the input and output layers.  Each hidden layer will usually have a bias neuron.



# Neuron Calculation

The output from a single neuron is calculated according to the following formula:

$ f(x,\theta) = \phi(\sum_i(\theta_i \cdot x_i)) $

The input vector ($x$) represents the feature vector and the vector $\theta$ (theta) represents the weights. To account for the bias neuron, a value of 1 is always appended to the end of the input feature vector.  This causes the last weight to be interpreted as a bias value that is simply added to the summation. The $\phi$ (phi) is the transfer/activation function. 

Consider using the above equation to calculate the output from the following neuron:

![Single Neuron](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_abstract_nn.png "Single Neuron")

The above neuron has 2 inputs plus the bias as a third.  This neuron might accept the following input feature vector:

```
[1,2]
```

To account for the bias neuron, a 1 is appended, as follows:

```
[1,2,1]
```

The weights for a 3-input layer (2 real inputs + bias) will always have an additional weight, for the bias.  A weight vector might be:

```
[ 0.1, 0.2, 0.3]
```

To calculate the summation, perform the following:

```
0.1*1 + 0.2*2 + 0.3*3 = 1.4
```

The value of 1.4 is passed to the $\phi$ (phi) function, which represents the activation function.



# Activation Functions

Activation functions, also known as transfer functions, are used to calculate the output of each layer of a neural network.  Historically neural networks have used a hyperbolic tangent, sigmoid/logistic, or linear activation function.  However, modern deep neural networks primarily make use of the following activation functions:

* **Rectified Linear Unit (ReLU)** - Used for the output of hidden layers.
* **Softmax** - Used for the output of classification neural networks. [Softmax Example](http://www.heatonresearch.com/aifh/vol3/softmax.html)
* **Linear** - Used for the output of regression neural networks (or 2-class classification).

The ReLU function is calculated as follows:

$ \phi(x) = \max(0, x) $

The Softmax is calculated as follows:

$ \phi_i(z) = \frac{e^{z_i}}{\sum\limits_{j \in group}e^{z_j}} $

The Softmax activation function is only useful with more than one output neuron.  It ensures that all of the output neurons sum to 1.0.  This makes it very useful for classification where it shows the probability of each of the classes as being the correct choice.

To experiment with the Softmax, click [here](http://www.heatonresearch.com/aifh/vol3/softmax.html).

The linear activation function is essentially no activation function:

$ \phi(x) = x $

For regression problems, this is the activation function of choice.  



# Why ReLU?

Why is the ReLU activation function so popular?  It was one of the key improvements to neural networks that makes deep learning work. Prior to deep learning, the sigmoid activation function was very common:

$ \phi(x) = \frac{1}{1 + e^{-x}} $

The graph of the sigmoid function is shown here:

![Sigmoid Activation Function](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_sigmoid.png "Sigmoid Activation Function")

Neural networks are often trained using gradient descent.  To make use of gradient descent, it is necessary to take the derivative of the activation function.  This allows the partial derivatives of each of the weights to be calculated with respect to the error function.  A derivative is the instantaneous rate of change:

![Derivative](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_deriv.png "Derivative")

The derivative of the sigmoid function is given here:

$ \phi'(x)=\phi(x)(1-\phi(x)) $

This derivative is often given in other forms.  The above form is used for computational efficiency. To see how this derivative was taken, see [this](http://www.heatonresearch.com/aifh/vol3/deriv_sigmoid.html).

The graph of the sigmoid derivative is given here:

![Sigmoid Derivative](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_deriv_sigmoid.png "Sigmoid Derivative")

The derivative quickly saturates to zero as *x* moves from zero.  This is not a problem for the derivative of the ReLU, which is given here:

$ \phi'(x) = \begin{cases} 1 & x > 0 \\ 0 & x \leq 0 \end{cases} $

# Why are Bias Neurons Needed?

The activation functions seen in the previous section specifies the output of a single neuron.  Together, the weight and bias of a neuron shape the output of the activation to produce the desired output.  To see how this process occurs, consider the following equation. It represents a single-input sigmoid activation neural network.

$ f(x,w,b) = \frac{1}{1 + e^{-(wx+b)}} $ 

The *x* variable represents the single input to the neural network.  The *w* and *b* variables specify the weight and bias of the neural network.  The above equation is a combination of the weighted sum of the inputs and the sigmoid activation function.  For this section, we will consider the sigmoid function because it clearly demonstrates the effect that a bias neuron has.

The weights of the neuron allow you to adjust the slope or shape of the activation function.  The following figure shows the effect on the output of the sigmoid activation function if the weight is varied:

![Adjusting Weight](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_bias_weight.png "Bias 1")

The above diagram shows several sigmoid curves using the following parameters:

```
f(x,0.5,0.0)
f(x,1.0,0.0)
f(x,1.5,0.0)
f(x,2.0,0.0)
```

To produce the curves, we did not use bias, which is evident in the third parameter of 0 in each case. Using four weight values yields four different sigmoid curves in the above figure. No matter the weight, we always get the same value of 0.5 when x is 0 because all of the curves hit the same point when x is 0.  We might need the neural network to produce other values when the input is near 0.5.  

Bias does shift the sigmoid curve, which allows values other than 0.5 when x is near 0. The following figure shows the effect of using a weight of 1.0 with several different biases:


![Adjusting Bias](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_bias_value.png "Bias 1")

The above diagram shows several sigmoid curves with the following parameters:

```
f(x,1.0,1.0)
f(x,1.0,0.5)
f(x,1.0,1.5)
f(x,1.0,2.0)
```

We used a weight of 1.0 for these curves in all cases.  When we utilized several different biases, sigmoid curves shifted to the left or right.  Because all the curves merge together at the top right or bottom left, it is not a complete shift.

When we put bias and weights together, they produced a curve that created the necessary output from a neuron.  The above curves are the output from only one neuron.  In a complete network, the output from many different neurons will combine to produce complex output patterns.

# TensorFlow - Google

![TensorFlow](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_tensorflow.png "TensorFlow")

TensorFlow is an open source software library for machine learning in various kinds of perceptual and language understanding tasks. It is currently used for both research and production by different teams in many commercial Google products, such as speech recognition, Gmail, Google Photos, and search, many of which had previously used its predecessor DistBelief. TensorFlow was originally developed by the Google Brain team for Google's research and production purposes and later released under the Apache 2.0 open source license on November 9, 2015.

* [TensorFlow Homepage](https://www.tensorflow.org/)
* [TensorFlow GitHib](https://github.com/tensorflow/tensorflow)
* [TensorFlow Google Groups Support](https://groups.google.com/forum/#!forum/tensorflow)
* [TensorFlow Google Groups Developer Discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/discuss)
* [TensorFlow FAQ](https://www.tensorflow.org/resources/faq)


# What version of TensorFlow do you have?

TensorFlow is very new and changing rapidly.  It is very important that you run the same version of it that I am using.  For this semester we will use TensorFlow 0.12.1. It is very important to have the right version of TensorFlow.

![Self Driving Car](http://imgc-cn.artprintimages.com/images/P-473-488-90/94/9475/CFB6500Z/posters/paul-noth-does-your-car-have-any-idea-why-my-car-pulled-it-over-new-yorker-cartoon.jpg)

[Wrong version of TensorFlow?](https://twitter.com/reza_zadeh/status/849160032608440320)

In [1]:
import tensorflow as tf
print("Tensor Flow Version: {}".format(tf.__version__))

Tensor Flow Version: 1.1.0


# Installing TensorFlow

* [IBM Data Scientist Workbench](datascientistworkbench.com) - All platforms, use your browser.
* Windows - Installing TensorFlow on Windows is not easy. Docker is your best option. [Hopefully this will improve in the future](https://github.com/tensorflow/tensorflow/issues/17).
* Mac - Supported platform.
* Linux - Supported platform.

[TensorFlow Setup Instructions](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#docker-based_installation)

# Why TensorFlow

* Supported by Google
* Works well on Linux/Mac
* Excellent GPU support
* Python is an easy to learn programming language
* Python is [extremely popular](http://www.kdnuggets.com/2014/08/four-main-languages-analytics-data-mining-data-science.html) in the data science community

# Other Deep Learning Tools
TensorFlow is not the only only game in town.  These are some of the best supported alternatives.  Most of these are written in C++. In order of my own preference (I have used all of these):

* [Theano](http://deeplearning.net/software/theano/) - Python, from the academics that created deep learning.  GPU support.
* [Computational Network Toolkit (CNTK)](https://github.com/Microsoft/CNTK) - Microsoft.  Support for Windows/Linux, command line only.  Bindings for predictions for C#/Python. GPU support.
* [Caffe](http://caffe.berkeleyvision.org/) Academic project from Berkeley.  Python.  
* [H2O](http://www.h2o.ai/) - Java based.  Supports all major platforms.  Limited support for computer vision. No GPU support.
* [Deeplearning4J](http://deeplearning4j.org/) - Java based. Supports all major platforms. GPU support in Java!
* [PaddlePaddle](https://github.com/baidu/Paddle) - [Baidu](http://www.baidu.com/)'s offering, very new.

# Other/Advanced Deep Learning

[Torch](http://torch.ch/) is used by Google DeepMind, the Facebook AI Research Group, IBM, Yandex and the Idiap Research Institute.  It has been used for some of the most advanced deep learning projects in the world.  However, it requires the [LUA](https://en.wikipedia.org/wiki/Lua_(programming_language)) programming language.  It is very advanced, but it is not mainstream.  I have not worked with Torch (yet!).

# Using TensorFlow

TensorFlow is a low-level mathematics API, similar to [Numpy](http://www.numpy.org/).  However, unlike Numpy, TensorFlow is built for deep learning.  TensorFlow works by allowing you to define compute graphs with Python.  In this regard, it is similar to [Spark](http://spark.apache.org/).  TensorFlow compiles these compute graphs into highly efficient C++/[CUDA](https://en.wikipedia.org/wiki/CUDA) code.

The [TensorBoard](https://www.tensorflow.org/versions/r0.10/how_tos/summaries_and_tensorboard/index.html) command line utility can be used to view these graphs.  The iris neural network's graph used in this class is shown here:

![Iris Graph](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_graph_tf.png "Iris Graph")

Expanding the DNN gives:


![Iris DNN Graph](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_graph_dnn.png "Iris DNN Graph")


# Using tf.contrib.learn

TF Learn ([**tf.contrib.learn**](https://www.tensorflow.org/tutorials/tflearn/)) (formerly SKFLOW) is a layer on top of Tensorflow that makes it much easier to create neural networks.  Rather than define the graphs, like you see above, you define the individual layers of the network with a much more high level API.  Unless you are performing research into entirely new structures of deep neural networks it is unlikely that you need to program TensorFlow directly.  

**For this class, we will use tf.contrib.learn, rather than direct TensorFlow**

tf.contrib.learn is built into TensorFlow (as of v0.8).  This makes it very easy to use.

All examples in this class will use tf.contrib.learn, and you are encouraged to use it for the programming assignments.

* [TF Learn API Docs](https://www.tensorflow.org/api_docs/python/contrib.learn/)
* [TF Learn Examples](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/learn)

# Helpful Functions for Tensorflow

The following functions will be used in conjunction with TensorFlow to help preprocess the data.  It is okay to just use them. For better understanding, try to understand how they work.

These functions allow you to build the feature vector for a neural network. Consider the following:

* Predictors/Inputs 
    * Fill any missing inputs with the median for that column.  Use **missing_median**.
    * Encode textual/categorical values with **encode_text_dummy**.
    * Encode numeric values with **encode_numeric_zscore**.
* Output
    * Discard rows with missing outputs.
    * Encode textual/categorical values with **encode_text_index**.
    * Do not encode output numeric values.
* Produce final feature vectors (x) and expected output (y) with **to_xy**.


In [127]:
def encode_text_dummy(df,name):
    dummies = pd.get_dummies(df[name])
    for x in dummies.columns:
        dummy_name = "{}-{}".format(name,x)
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True)
    
encode_text_dummy(df,"species")

In [128]:
df

sepal_l   sepal_w   petal_l   petal_w  species-0  species-1  species-2
0   -0.897674  1.015602 -1.335752 -1.311052          1          0          0
1   -1.139200 -0.131539 -1.335752 -1.311052          1          0          0
2   -1.380727  0.327318 -1.392399 -1.311052          1          0          0
3   -1.501490  0.097889 -1.279104 -1.311052          1          0          0
4   -1.018437  1.245030 -1.335752 -1.311052          1          0          0
5   -0.535384  1.933315 -1.165809 -1.048667          1          0          0
6   -1.501490  0.786174 -1.335752 -1.179859          1          0          0
7   -1.018437  0.786174 -1.279104 -1.311052          1          0          0
8   -1.743017 -0.360967 -1.335752 -1.311052          1          0          0
9   -1.139200  0.097889 -1.279104 -1.442245          1          0          0
10  -0.535384  1.474458 -1.279104 -1.311052          1          0          0
11  -1.259964  0.786174 -1.222456 -1.311052          1          0          0
12  -1.259964 -0.131539 -1.335752 -1.442245          1          0          0
13  -1.863780 -0.131539 -1.505695 -1.442245          1          0          0
14  -0.052331  2.162743 -1.449047 -1.311052          1          0          0
15  -0.173094  3.080455 -1.279104 -1.048667          1          0          0
16  -0.535384  1.933315 -1.392399 -1.048667          1          0          0
17  -0.897674  1.015602 -1.335752 -1.179859          1          0          0
18  -0.173094  1.703886 -1.165809 -1.179859          1          0          0
19  -0.897674  1.703886 -1.279104 -1.179859          1          0          0
20  -0.535384  0.786174 -1.165809 -1.311052          1          0          0
21  -0.897674  1.474458 -1.279104 -1.048667          1          0          0
22  -1.501490  1.245030 -1.562342 -1.311052          1          0          0
23  -0.897674  0.556746 -1.165809 -0.917474          1          0          0
24  -1.259964  0.786174 -1.052513 -1.311052          1          0          0
25  -1.018437 -0.131539 -1.222456 -1.311052          1          0          0
26  -1.018437  0.786174 -1.222456 -1.048667          1          0          0
27  -0.776911  1.015602 -1.279104 -1.311052          1          0          0
28  -0.776911  0.786174 -1.335752 -1.311052          1          0          0
29  -1.380727  0.327318 -1.222456 -1.311052          1          0          0
..        ...       ...       ...       ...        ...        ...        ...
120  1.276066  0.327318  1.100097  1.443994          0          0          1
121 -0.293857 -0.590395  0.646916  1.050416          0          0          1
122  2.242172 -0.590395  1.666574  1.050416          0          0          1
123  0.551486 -0.819823  0.646916  0.788031          0          0          1
124  1.034539  0.556746  1.100097  1.181609          0          0          1
125  1.638355  0.327318  1.270040  0.788031          0          0          1
126  0.430722 -0.590395  0.590269  0.788031          0          0          1
127  0.309959 -0.131539  0.646916  0.788031          0          0          1
128  0.672249 -0.590395  1.043450  1.181609          0          0          1
129  1.638355 -0.131539  1.156745  0.525645          0          0          1
130  1.879882 -0.590395  1.326688  0.919223          0          0          1
131  2.483699  1.703886  1.496631  1.050416          0          0          1
132  0.672249 -0.590395  1.043450  1.312801          0          0          1
133  0.551486 -0.590395  0.760211  0.394453          0          0          1
134  0.309959 -1.049251  1.043450  0.263260          0          0          1
135  2.242172 -0.131539  1.326688  1.443994          0          0          1
136  0.551486  0.786174  1.043450  1.575187          0          0          1
137  0.672249  0.097889  0.986802  0.788031          0          0          1
138  0.189196 -0.131539  0.590269  0.788031          0          0          1
139  1.276066  0.097889  0.930154  1.181609          0          0          1
14

In [218]:
from sklearn import preprocessing
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shutil
import tensorflow.contrib.keras as keras


# function that checks for NaN in a pandas df
def check_nan(df):
    count = 0
    for i,j in enumerate(df.isnull().sum()):
        if j != 0:
            print(df.columns[i], "contains {} NaN".format(j))
            count += 1
    if count == 0:
        print("no NaN")
        




# Encode text values to dummy variables(i.e. [1,0,0],[0,1,0],[0,0,1] for red,green,blue)
def encode_text_dummy(df,name):
    dummies = pd.get_dummies(df[name])
    for x in dummies.columns:
        dummy_name = "{}-{}".format(name,x)
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True)

# Encode text values to a single dummy variable.  The new columns (which do not replace the old) will have a 1
# at every location where the origional column (name) matches each of the target_values.  One column is added for
# each target value.
def encode_text_single_dummy(df,name,target_values):
    for tv in target_values:
        l = list(df[name].astype(str))
        l = [1 if str(x)==str(tv) else 0 for x in l]
        name2 = "{}-{}".format(name,tv)
        df[name2] = l
    
# Encode text values to indexes(i.e. [1],[2],[3] for red,green,blue).
def encode_text_index(df,name):
    le = preprocessing.LabelEncoder()
    df[name] = le.fit_transform(df[name])
    return le.classes_

# Encode a numeric column as zscores
def encode_numeric_zscore(df,name,mean=None,sd=None):
    if mean is None:
        mean = df[name].mean()

    if sd is None:
        sd = df[name].std()

    df[name] = (df[name]-mean)/sd

# Convert all missing values in the specified column to the median
def missing_median(df, name):
    med = df[name].median()
    df[name] = df[name].fillna(med)

# Convert a Pandas dataframe to the x,y inputs that TensorFlow needs.
def to_xy(df,target):
    result = []
    for x in df.columns:
        if x != target:
            result.append(x)

    # find out the type of the target column.  Is it really this hard? :(
    target_type = df[target].dtypes
    target_type = target_type[0] if hasattr(target_type, '__iter__') else target_type
    
    # Encode to int for classification, float otherwise. TensorFlow likes 32 bits.
    if target_type in (np.int64, np.int32):
        # Classification
        return df.as_matrix(result).astype(np.float32),df.as_matrix([target]).astype(np.int32)
    else:
        # Regression
        return df.as_matrix(result).astype(np.float32),df.as_matrix([target]).astype(np.float32)
    
######
# my version with target variable being encoded as one-hot-encoder
######
def to_xy_one_hot(df1,target):
    result = []
    for x in df.columns:
        if x != target:
            result.append(x)

    # find out the type of the target column.  Is it really this hard? :(
    target_type = df[target].dtypes
    target_type = target_type[0] if hasattr(target_type, '__iter__') else target_type
    
    # Encode to int for classification, float otherwise. TensorFlow likes 32 bits.
    if target_type in (np.int64, np.int32):
        # Classification
        return df.as_matrix(result).astype(np.float32), \
               keras.utils.to_categorical(df.as_matrix([target])).astype(np.int32)
    else:
        # Regression
        return df.as_matrix(result).astype(np.float32),df.as_matrix([target]).astype(np.float32)
    
##############

# Nicely formatted time string
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return "{}:{:>02}:{:>05.2f}".format(h, m, s)

# Regression chart, we will see more of this chart in the next class.
def chart_regression(pred,y):
    t = pd.DataFrame({'pred' : pred, 'y' : y_test.flatten()})
    t.sort_values(by=['y'],inplace=True)
    a = plt.plot(t['y'].tolist(),label='expected')
    b = plt.plot(t['pred'].tolist(),label='prediction')
    plt.ylabel('output')
    plt.legend()
    plt.show()
    
# Get a new directory to hold checkpoints from a neural network.  This allows the neural network to be
# loaded later.  If the erase param is set to true, the contents of the directory will be cleared.
def get_model_dir(name,erase):
    base_path = os.path.join(".","dnn")
    model_dir = os.path.join(base_path,name)
    os.makedirs(model_dir,exist_ok=True)
    if erase and len(model_dir)>4 and os.path.isdir(model_dir):
        shutil.rmtree(model_dir,ignore_errors=True) # be careful, this deletes everything below the specified path
    return model_dir



# Simple TensorFlow Classification: Iris

This is a very simple example of how to perform the Iris classification using TensorFlow.  The iris.csv file is used, rather than using the built-in files that many of the Google examples require.  

**Make sure that you always run previous code blocks.  If you run the code block below, without the codeblock above, you will get errors**

In [309]:
import tensorflow as tf
import tensorflow.contrib.learn as learn
from sklearn import metrics
import pandas as pd
import os
from sklearn import preprocessing

path = "./data/"

# Read iris dataset
filename_read = os.path.join(path,"iris.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])

# Extract just the columns we shall predict on
encode_numeric_zscore(df,'sepal_l')
encode_numeric_zscore(df,'sepal_w')
encode_numeric_zscore(df,'petal_l')
encode_numeric_zscore(df,'petal_w')
species = encode_text_index(df,'species')
num_classes = len(species)

# Create x(predictors) and y (expected outcome)
x,y = to_xy(df,'species')

# Get/clear a directory to store the neural network to
model_dir = get_model_dir('iris',True)

# Create a deep neural network with 3 hidden layers of 10, 20, 5
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=x.shape[1])]
classifier = learn.DNNClassifier(
    model_dir= model_dir,
    hidden_units=[10, 20, 5], n_classes=num_classes, feature_columns=feature_columns)

# Might be needed in future versions of "TensorFlow Learn"
#classifier = learn.SKCompat(classifier) # For Sklearn compatibility

# Fit/train neural network
classifier.fit(x, y, steps=1000)

# Measure accuracy
pred = list(classifier.predict(x, as_iterable=True))
score = metrics.accuracy_score(y, pred)
print("Final score: {}".format(score))

# How to convert predicted indexs to category labels (e.g. iris names)
predDF = pd.DataFrame(pred)
pred_nameDF = pd.DataFrame(species[pred])
actual_nameDF = pd.DataFrame(species[df['species']])
df2 = pd.concat([df,predDF,pred_nameDF,actual_nameDF],axis=1)
df2.columns = ['sepal_l','sepal_w','petal_l','petal_w','expected','predicted','expected_str','predicted_str']
df2[70:72]

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_tf_random_seed': None, '_master': '', '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_num_worker_replicas': 0, '_save_checkpoints_steps': None, '_is_chief': True, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f10390d3630>, '_model_dir': None, '_save_summary_steps': 100, '_environment': 'local', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_evaluation_master': '', '_task_id': 0, '_keep_checkpoint_every_n_hours': 10000}
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving 

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py:248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  equality = a == b


INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into ./dnn/iris/model.ckpt.
INFO:tensorflow:step = 1, loss = 1.0985
INFO:tensorflow:global_step/sec: 918.778
INFO:tensorflow:step = 101, loss = 0.156033 (0.110 sec)
INFO:tensorflow:global_step/sec: 929.329
INFO:tensorflow:step = 201, loss = 0.0554466 (0.108 sec)
INFO:tensorflow:global_step/sec: 884.693
INFO:tensorflow:step = 301, loss = 0.042626 (0.115 sec)
INFO:tensorflow:global_step/sec: 845.472
INFO:tensorflow:step = 401, loss = 0.0381936 (0.116 sec)
INFO:tensorflow:global_step/sec: 1009.47
INFO:tensorflow:step = 501, loss = 0.0358881 (0.099 sec)
INFO:tensorflow:global_step/sec: 981.787
INFO:tensorflow:step = 601, loss = 0.0342043 (0.102 sec)
INFO:tensorflow:global_step/sec: 1021.31
INFO:tensorflow:step = 701, loss = 0.0325412 (0.098 sec)
INFO:tensorflow:global_step/sec: 997.086
INFO:tensorflow:step = 801, loss = 0.0308267 (0.101 sec)
INFO:tensorflow:global_step/sec: 1014.17
INFO:tensorflow:step = 9

sepal_l   sepal_w   petal_l   petal_w  expected  predicted  \
70  0.068433  0.327318  0.590269  0.788031         1          1   
71  0.309959 -0.590395  0.137087  0.132067         1          1   

       expected_str    predicted_str  
70  Iris-versicolor  Iris-versicolor  
71  Iris-versicolor  Iris-versicolor

In [95]:
feature_columns

[_RealValuedColumn(column_name='', dimension=4, default_value=None, dtype=tf.float32, normalizer=None)]

Notice the massive amount of warnings and other information that you are given?  All of the warnings do not apply, and are just "growing pains" of the rapid pace of the various parts of TensorFlow.  It can be helpful to instruct TensorFlow to only display errors.  The following code accomplishes this.  Run the line below and then return the above example.

In [173]:
tf.contrib.keras.layers

<module 'tensorflow.contrib.keras.api.keras.layers' from '/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/keras/api/keras/layers/__init__.py'>

In [98]:
# Only show errors
tf.logging.set_verbosity(tf.logging.ERROR)

Of course, while debugging, you might like to see all of the information.  The following command turns the output back on.

In [99]:
# Only show errors
tf.logging.set_verbosity(tf.logging.INFO)

Now that you have a neural network trained, we would like to be able to use it.  The following code makes use of our neural network.

In [312]:
tf.logging.set_verbosity(tf.logging.ERROR)


# ad hoc prediction
sample_flower = np.array( [[-1.501490,0.097889,-1.279104,-1.311052]], dtype=float)
pred = list(classifier.predict(sample_flower, as_iterable=True))
print("Predict that {} is: {}".format(sample_flower,species[pred]))

# predict two sample flowers
sample_flower = np.array( [[1.0, 2., 3., 1.],[5.0,3.0,4.0,2.0],[5.2,3.5,1.5,0.8]], dtype=float)
pred = list(classifier.predict(sample_flower, as_iterable=True))
print("Predict that {} is: {}".format(sample_flower,species[pred]))

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py:248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  equality = a == b


Predict that [[-1.5015  0.0979 -1.2791 -1.3111]] is: ['Iris-setosa']
Predict that [[ 1.   2.   3.   1. ]
 [ 5.   3.   4.   2. ]
 [ 5.2  3.5  1.5  0.8]] is: ['Iris-virginica' 'Iris-virginica' 'Iris-virginica']


### Keras version of the tf.learn code for a simple DNN classifier
as it seems, the tf.learn DNN uses layers of fully connected layers with `Relu` activation function
I had to convert the target variables to on-hot-encoder

In [305]:
import tensorflow.contrib.keras as keras # tensorflow version for this case is v1.1
import tensorflow as tf
import pandas as pd
import os

path = "./data/"

# Read iris dataset
filename_read = os.path.join(path,"iris.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])

# Extract just the columns we shall predict on
# convert originald data to zscores for input variables
encode_numeric_zscore(df,'sepal_l')
encode_numeric_zscore(df,'sepal_w')
encode_numeric_zscore(df,'petal_l')
encode_numeric_zscore(df,'petal_w')
# encode target "species" column from string to numeric values
species = encode_text_index(df,'species')

# Create x(predictors) and y (expected outcome)
x,y = to_xy(df,'species')
# encode the target numeric valus to one-hot-encoder
y_categorical = keras.utils.to_categorical(y)


model = keras.models.Sequential()
model.add(keras.layers.Dense(20, input_shape=(x.shape[1],)))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dense(10))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dense(5))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dense(3))
model.add(keras.layers.Activation('softmax'))
model.summary()
model.compile(loss='categorical_crossentropy',
                optimizer=keras.optimizers.Adagrad(lr=0.1),
                metrics=['accuracy'])
history = model.fit(x, y_categorical,
batch_size=150, epochs=1000,
verbose=1)

# here it should go test data
score = model.evaluate(x, y_categorical, verbose=1)
print("\nTest loss:", score[0])
print('Test accuracy:', score[1])


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_153 (Dense)            (None, 20)                100       
_________________________________________________________________
activation_95 (Activation)   (None, 20)                0         
_________________________________________________________________
dense_154 (Dense)            (None, 10)                210       
_________________________________________________________________
activation_96 (Activation)   (None, 10)                0         
_________________________________________________________________
dense_155 (Dense)            (None, 5)                 55        
_________________________________________________________________
activation_97 (Activation)   (None, 5)                 0         
_________________________________________________________________
dense_156 (Dense)            (None, 3)                 18        
__________

150/150 [==============================] - 0s - loss: 0.0775 - acc: 0.9867
Epoch 78/1000
150/150 [==============================] - 0s - loss: 0.0764 - acc: 0.9933
Epoch 79/1000
150/150 [==============================] - 0s - loss: 0.0784 - acc: 0.9867
Epoch 80/1000
150/150 [==============================] - 0s - loss: 0.0848 - acc: 0.9867
Epoch 81/1000
150/150 [==============================] - 0s - loss: 0.0736 - acc: 0.9867
Epoch 82/1000
150/150 [==============================] - 0s - loss: 0.0716 - acc: 0.9933
Epoch 83/1000
150/150 [==============================] - 0s - loss: 0.0713 - acc: 0.9867
Epoch 84/1000
150/150 [==============================] - 0s - loss: 0.0734 - acc: 0.9933
Epoch 85/1000
150/150 [==============================] - 0s - loss: 0.0773 - acc: 0.9867
Epoch 86/1000
150/150 [==============================] - 0s - loss: 0.0890 - acc: 0.9800
Epoch 87/1000
150/150 [==============================] - 0s - loss: 0.0703 - acc: 0.9867
Epoch 88/1000
150/150 [============

150/150 [==============================] - 0s - loss: 0.0347 - acc: 1.0000
Epoch 169/1000
150/150 [==============================] - 0s - loss: 0.0358 - acc: 0.9933
Epoch 170/1000
150/150 [==============================] - 0s - loss: 0.0346 - acc: 1.0000
Epoch 171/1000
150/150 [==============================] - 0s - loss: 0.0354 - acc: 0.9933
Epoch 172/1000
150/150 [==============================] - 0s - loss: 0.0342 - acc: 1.0000
Epoch 173/1000
150/150 [==============================] - 0s - loss: 0.0342 - acc: 0.9933
Epoch 174/1000
150/150 [==============================] - 0s - loss: 0.0323 - acc: 1.0000
Epoch 175/1000
150/150 [==============================] - 0s - loss: 0.0324 - acc: 1.0000
Epoch 176/1000
150/150 [==============================] - 0s - loss: 0.0318 - acc: 1.0000
Epoch 177/1000
150/150 [==============================] - 0s - loss: 0.0320 - acc: 1.0000
Epoch 178/1000
150/150 [==============================] - 0s - loss: 0.0313 - acc: 1.0000
Epoch 179/1000
150/150 [=

150/150 [==============================] - 0s - loss: 0.0194 - acc: 1.0000
Epoch 260/1000
150/150 [==============================] - 0s - loss: 0.0194 - acc: 1.0000
Epoch 261/1000
150/150 [==============================] - 0s - loss: 0.0193 - acc: 1.0000
Epoch 262/1000
150/150 [==============================] - 0s - loss: 0.0192 - acc: 1.0000
Epoch 263/1000
150/150 [==============================] - 0s - loss: 0.0191 - acc: 1.0000
Epoch 264/1000
150/150 [==============================] - 0s - loss: 0.0190 - acc: 1.0000
Epoch 265/1000
150/150 [==============================] - 0s - loss: 0.0189 - acc: 1.0000
Epoch 266/1000
150/150 [==============================] - 0s - loss: 0.0188 - acc: 1.0000
Epoch 267/1000
150/150 [==============================] - 0s - loss: 0.0187 - acc: 1.0000
Epoch 268/1000
150/150 [==============================] - 0s - loss: 0.0187 - acc: 1.0000
Epoch 269/1000
150/150 [==============================] - 0s - loss: 0.0186 - acc: 1.0000
Epoch 270/1000
150/150 [=

150/150 [==============================] - 0s - loss: 0.0141 - acc: 1.0000
Epoch 351/1000
150/150 [==============================] - 0s - loss: 0.0140 - acc: 1.0000
Epoch 352/1000
150/150 [==============================] - 0s - loss: 0.0140 - acc: 1.0000
Epoch 353/1000
150/150 [==============================] - 0s - loss: 0.0139 - acc: 1.0000
Epoch 354/1000
150/150 [==============================] - 0s - loss: 0.0139 - acc: 1.0000
Epoch 355/1000
150/150 [==============================] - 0s - loss: 0.0139 - acc: 1.0000
Epoch 356/1000
150/150 [==============================] - 0s - loss: 0.0138 - acc: 1.0000
Epoch 357/1000
150/150 [==============================] - 0s - loss: 0.0138 - acc: 1.0000
Epoch 358/1000
150/150 [==============================] - 0s - loss: 0.0137 - acc: 1.0000
Epoch 359/1000
150/150 [==============================] - 0s - loss: 0.0137 - acc: 1.0000
Epoch 360/1000
150/150 [==============================] - 0s - loss: 0.0137 - acc: 1.0000
Epoch 361/1000
150/150 [=

150/150 [==============================] - 0s - loss: 0.0111 - acc: 1.0000
Epoch 442/1000
150/150 [==============================] - 0s - loss: 0.0111 - acc: 1.0000
Epoch 443/1000
150/150 [==============================] - 0s - loss: 0.0111 - acc: 1.0000
Epoch 444/1000
150/150 [==============================] - 0s - loss: 0.0110 - acc: 1.0000
Epoch 445/1000
150/150 [==============================] - 0s - loss: 0.0110 - acc: 1.0000
Epoch 446/1000
150/150 [==============================] - 0s - loss: 0.0110 - acc: 1.0000
Epoch 447/1000
150/150 [==============================] - 0s - loss: 0.0110 - acc: 1.0000
Epoch 448/1000
150/150 [==============================] - 0s - loss: 0.0109 - acc: 1.0000
Epoch 449/1000
150/150 [==============================] - 0s - loss: 0.0109 - acc: 1.0000
Epoch 450/1000
150/150 [==============================] - 0s - loss: 0.0109 - acc: 1.0000
Epoch 451/1000
150/150 [==============================] - 0s - loss: 0.0109 - acc: 1.0000
Epoch 452/1000
150/150 [=

150/150 [==============================] - 0s - loss: 0.0092 - acc: 1.0000
Epoch 533/1000
150/150 [==============================] - 0s - loss: 0.0092 - acc: 1.0000
Epoch 534/1000
150/150 [==============================] - 0s - loss: 0.0091 - acc: 1.0000
Epoch 535/1000
150/150 [==============================] - 0s - loss: 0.0091 - acc: 1.0000
Epoch 536/1000
150/150 [==============================] - 0s - loss: 0.0091 - acc: 1.0000
Epoch 537/1000
150/150 [==============================] - 0s - loss: 0.0091 - acc: 1.0000
Epoch 538/1000
150/150 [==============================] - 0s - loss: 0.0091 - acc: 1.0000
Epoch 539/1000
150/150 [==============================] - 0s - loss: 0.0091 - acc: 1.0000
Epoch 540/1000
150/150 [==============================] - 0s - loss: 0.0090 - acc: 1.0000
Epoch 541/1000
150/150 [==============================] - 0s - loss: 0.0090 - acc: 1.0000
Epoch 542/1000
150/150 [==============================] - 0s - loss: 0.0090 - acc: 1.0000
Epoch 543/1000
150/150 [=

150/150 [==============================] - 0s - loss: 0.0078 - acc: 1.0000
Epoch 624/1000
150/150 [==============================] - 0s - loss: 0.0078 - acc: 1.0000
Epoch 625/1000
150/150 [==============================] - 0s - loss: 0.0078 - acc: 1.0000
Epoch 626/1000
150/150 [==============================] - 0s - loss: 0.0078 - acc: 1.0000
Epoch 627/1000
150/150 [==============================] - 0s - loss: 0.0078 - acc: 1.0000
Epoch 628/1000
150/150 [==============================] - 0s - loss: 0.0078 - acc: 1.0000
Epoch 629/1000
150/150 [==============================] - 0s - loss: 0.0077 - acc: 1.0000
Epoch 630/1000
150/150 [==============================] - 0s - loss: 0.0078 - acc: 1.0000
Epoch 631/1000
150/150 [==============================] - 0s - loss: 0.0077 - acc: 1.0000
Epoch 632/1000
150/150 [==============================] - 0s - loss: 0.0077 - acc: 1.0000
Epoch 633/1000
150/150 [==============================] - 0s - loss: 0.0077 - acc: 1.0000
Epoch 634/1000
150/150 [=

150/150 [==============================] - 0s - loss: 0.0068 - acc: 1.0000
Epoch 715/1000
150/150 [==============================] - 0s - loss: 0.0068 - acc: 1.0000
Epoch 716/1000
150/150 [==============================] - 0s - loss: 0.0068 - acc: 1.0000
Epoch 717/1000
150/150 [==============================] - 0s - loss: 0.0068 - acc: 1.0000
Epoch 718/1000
150/150 [==============================] - 0s - loss: 0.0068 - acc: 1.0000
Epoch 719/1000
150/150 [==============================] - 0s - loss: 0.0068 - acc: 1.0000
Epoch 720/1000
150/150 [==============================] - 0s - loss: 0.0068 - acc: 1.0000
Epoch 721/1000
150/150 [==============================] - 0s - loss: 0.0068 - acc: 1.0000
Epoch 722/1000
150/150 [==============================] - 0s - loss: 0.0067 - acc: 1.0000
Epoch 723/1000
150/150 [==============================] - 0s - loss: 0.0067 - acc: 1.0000
Epoch 724/1000
150/150 [==============================] - 0s - loss: 0.0067 - acc: 1.0000
Epoch 725/1000
150/150 [=

150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 806/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 807/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 808/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 809/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 810/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 811/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 812/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 813/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 814/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 815/1000
150/150 [==============================] - 0s - loss: 0.0060 - acc: 1.0000
Epoch 816/1000
150/150 [=

150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 897/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 898/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 899/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 900/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 901/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 902/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 903/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 904/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 905/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 906/1000
150/150 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 907/1000
150/150 [=

150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 988/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 989/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 990/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 991/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 992/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 993/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 994/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 995/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 996/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 997/1000
150/150 [==============================] - 0s - loss: 0.0049 - acc: 1.0000
Epoch 998/1000
150/150 [=

In [8]:
# How to convert predicted indexs to category labels (e.g. iris names) and create new df with original
# and newly predicted values in order to easily compare the results
pred_k = model.predict_classes(x)
predDF_k = pd.DataFrame(pred_k)
pred_nameDF_k = pd.DataFrame(species[pred_k])
actual_nameDF_k = pd.DataFrame(species[df['species']])
df2_k = pd.concat([df, predDF_k,pred_nameDF_k,actual_nameDF_k],axis=1)
# we create df2_k["one_hot"] column from three columns created by y_categorical cast to Dataframe
# since it would give us three separate columns, we create one unique column by converting values
# to str and concatenating them
df2_k['one_hot'] = '[' + pd.DataFrame(y_categorical)[0].map(str) + ',' + pd.DataFrame(y_categorical)[1].map(str) \
+ ',' + pd.DataFrame(y_categorical)[2].map(str) + ']'  
df2_k.columns = ['sepal_l','sepal_w','petal_l','petal_w', 'expected', 'predicted','expected_str','predicted_str',\
                 'one_hot']

df2_k.head()

 32/150 [=====>........................] - ETA: 0s

sepal_l   sepal_w   petal_l   petal_w  expected  predicted expected_str  \
0 -0.897674  1.015602 -1.335752 -1.311052         0          0  Iris-setosa   
1 -1.139200 -0.131539 -1.335752 -1.311052         0          0  Iris-setosa   
2 -1.380727  0.327318 -1.392399 -1.311052         0          0  Iris-setosa   
3 -1.501490  0.097889 -1.279104 -1.311052         0          0  Iris-setosa   
4 -1.018437  1.245030 -1.335752 -1.311052         0          0  Iris-setosa   

  predicted_str        one_hot  
0   Iris-setosa  [1.0,0.0,0.0]  
1   Iris-setosa  [1.0,0.0,0.0]  
2   Iris-setosa  [1.0,0.0,0.0]  
3   Iris-setosa  [1.0,0.0,0.0]  
4   Iris-setosa  [1.0,0.0,0.0]

In [9]:
# making ah-hoc predictions of flowers in keras
# make sure to add dtype=float so it works properly
sample_flower_k = np.array([[-1.501490,0.097889,-1.279104,-1.311052]], dtype=float)
pred = list(model.predict_classes(sample_flower_k))
print("Predict that {} is: {}".format(sample_flower_k,species[pred]))

# predict two sample flowers
sample_flower_k = np.array( [[0.06,0.3,0.5,0.7],[5.0,3.0,4.0,2.0],[-1.50,0.10,-1.27,-1.3]], dtype=float)
pred = model.predict_classes(sample_flower_k)
print("Predict that {} is: {}".format(sample_flower_k,species[pred]))

1/1 [==============================] - 0s
Predict that [[-1.50149   0.097889 -1.279104 -1.311052]] is: ['Iris-setosa']
3/3 [==============================] - 0s
Predict that [[ 0.06  0.3   0.5   0.7 ]
 [ 5.    3.    4.    2.  ]
 [-1.5   0.1  -1.27 -1.3 ]] is: ['Iris-versicolor' 'Iris-virginica' 'Iris-setosa']


In [307]:
from IPython.display import display

# Don't display numpy in scientific notation
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

# Generate predictions
pred = list(model.predict_proba(x))

print("\nNumpy array of predictions")
print(pred[0]*100)

print("As percent probability")
display(pred[0:5])

# logarithmic loss - useful for penalizing wrong answers

score = metrics.log_loss(y_categorical, pred)
print("Log loss score: {}".format(score))

 32/150 [=====>........................] - ETA: 0s
Numpy array of predictions
[ 100.    0.    0.]
As percent probability


[array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32)]

Log loss score: 0.0048522568284682654


In [308]:
pred

[array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),
 array([ 1.,  0.,  0.], dtype=float32),


# Simple TensorFlow Regression: MPG

This example shows how to encode the MPG dataset for regression.  This is slightly more complex than Iris, because:

* Input has both numeric and categorical
* Input has missing values

To encode categorical values that are part of the feature vector, use the functions from above.  If the categorical value is the target (as was the case with Iris, use the same technique as Iris). The iris technique allows you to decode back to Iris text strings from the predictions.

In [40]:
filename_read = os.path.join(path,"auto-mpg.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])



horsepower contains 6 NaN


In [19]:
df.columns[3]

'horsepower'

In [83]:
import tensorflow.contrib.learn as skflow
import pandas as pd
import os
import numpy as np
from sklearn import metrics
from scipy.stats import zscore

path = "./data/"

filename_read = os.path.join(path,"auto-mpg.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])

print(df.info())



# create feature vector
missing_median(df, 'horsepower')
df.drop('name',1,inplace=True)
encode_numeric_zscore(df, 'horsepower')
encode_numeric_zscore(df, 'weight')
encode_numeric_zscore(df, 'cylinders')
encode_numeric_zscore(df, 'displacement')
encode_numeric_zscore(df, 'acceleration')
encode_text_dummy(df, 'origin')


# Display training data
df

# Encode to a 2D matrix for training
x,y = to_xy(df,'mpg')

# Get/clear a directory to store the neural network to
model_dir = get_model_dir('mpg',True)

# Create a deep neural network with 3 hidden layers of 50, 25, 10
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=x.shape[1])]
regressor = skflow.DNNRegressor(
    model_dir= model_dir,
    feature_columns=feature_columns,
    hidden_units=[50, 25, 10])

# Fit/train neural network
regressor.fit(x, y,steps=1000)

# Measure RMSE error.  RMSE is common for regression.
pred = list(regressor.predict(x, as_iterable=True))
score = np.sqrt(metrics.mean_squared_error(pred,y))
print("###########################")
print("Final score (RMSE): {}".format(score))
print("###########################")

# How to make many predictions
pred = list(regressor.predict(x, as_iterable=True))
predDF = pd.DataFrame(pred)
df2 = pd.concat([df,predDF,pd.DataFrame(y)],axis=1)

df2.columns = list(df.columns)+['pred','ideal']
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
mpg             398 non-null float64
cylinders       398 non-null int64
displacement    398 non-null float64
horsepower      392 non-null float64
weight          398 non-null int64
acceleration    398 non-null float64
year            398 non-null int64
origin          398 non-null int64
name            398 non-null object
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB
None
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_tf_random_seed': None, '_master': '', '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_num_worker_replicas': 0, '_save_checkpoints_steps': None, '_is_chief': True, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1051ca7da0>, '_model_dir': None, '_save_summary_steps': 100, '_environment': 'local', '_tf_config': gpu_options {
  per_process_gpu_m

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py:248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  equality = a == b


INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into ./dnn/mpg/model.ckpt.
INFO:tensorflow:step = 1, loss = 696.166
INFO:tensorflow:global_step/sec: 550.763
INFO:tensorflow:step = 101, loss = 14.6417 (0.183 sec)
INFO:tensorflow:global_step/sec: 567.048
INFO:tensorflow:step = 201, loss = 13.8166 (0.177 sec)
INFO:tensorflow:global_step/sec: 541.093
INFO:tensorflow:step = 301, loss = 13.255 (0.184 sec)
INFO:tensorflow:global_step/sec: 542.325
INFO:tensorflow:step = 401, loss = 11.8842 (0.184 sec)
INFO:tensorflow:global_step/sec: 544.556
INFO:tensorflow:step = 501, loss = 11.441 (0.184 sec)
INFO:tensorflow:global_step/sec: 538.507
INFO:tensorflow:step = 601, loss = 11.1914 (0.187 sec)
INFO:tensorflow:global_step/sec: 552.993
INFO:tensorflow:step = 701, loss = 11.2842 (0.180 sec)
INFO:tensorflow:global_step/sec: 565.506
INFO:tensorflow:step = 801, loss = 10.9817 (0.177 sec)
INFO:tensorflow:global_step/sec: 549.351
INFO:tensorflow:step = 901, loss = 10.89

mpg  cylinders  displacement  horsepower    weight  acceleration  year  \
0  18.0   1.496308      1.089233    0.672271  0.630077     -1.293870    70   
1  15.0   1.496308      1.501624    1.587959  0.853259     -1.475181    70   
2  18.0   1.496308      1.194728    1.195522  0.549778     -1.656492    70   
3  16.0   1.496308      1.060461    1.195522  0.546236     -1.293870    70   
4  17.0   1.496308      1.041280    0.933897  0.565130     -1.837804    70   

   origin-1  origin-2  origin-3       pred  ideal  
0         1         0         0  16.809656   18.0  
1         1         0         0  13.925308   15.0  
2         1         0         0  15.844979   18.0  
3         1         0         0  15.498699   16.0  
4         1         0         0  16.843414   17.0

### Simple Regression: MPG with keras

In [281]:
import tensorflow.contrib.keras as keras # tensorflow version for this case is v1.1
# from tensorflow.contrib.keras.layers import Input
import pandas as pd
import os
import numpy as np
from sklearn import metrics
from scipy.stats import zscore

path = "./data/"

filename_read = os.path.join(path,"auto-mpg.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])

print(df.info())
print(df.describe())


# create feature vector
missing_median(df, 'horsepower')
df.drop('name',1,inplace=True)
encode_numeric_zscore(df, 'horsepower')
encode_numeric_zscore(df, 'weight')
encode_numeric_zscore(df, 'cylinders')
encode_numeric_zscore(df, 'displacement')
encode_numeric_zscore(df, 'acceleration')
encode_text_dummy(df, 'origin')


# Display training data
df

# Encode to a 2D matrix for training
x,y = to_xy(df,'mpg')

# Get/clear a directory to store the neural network to
model_dir = get_model_dir('mpg',True)

# Create a deep neural network with 3 hidden layers of 50, 25, 10

## this way is how the book "deep learning with keras" describes
# features = keras.layers.Input(shape=(9,))
# nn = keras.layers.Dense(50, activation="relu", kernel_initializer="glorot_uniform")(features)
# nn = keras.layers.Dense(25, activation="relu", kernel_initializer="glorot_uniform")(nn)
# nn = keras.layers.Dense(10, activation="relu", kernel_initializer="glorot_uniform")(nn)
# mpg = keras.layers.Dense(1, kernel_initializer="glorot_uniform")(nn)

# model = keras.models.Model(inputs=[features], outputs=[mpg])
# model.compile(loss="mse", optimizer="adam")

# # train network
# NUM_EPOCHS = 1000
# BATCH_SIZE = 64

# history = model.fit(x, y, batch_size=BATCH_SIZE, epochs=NUM_EPOCHS)


## this was is how I've seen model being constructed in other examples - for now I prefer this one

model = keras.models.Sequential()
model.add(keras.layers.Dense(50, input_dim=x.shape[1], kernel_initializer="glorot_uniform"))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dense(25, kernel_initializer="glorot_uniform"))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dense(10, kernel_initializer="glorot_uniform"))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dense(1))
model.summary()
model.compile(loss='mse',
                optimizer=keras.optimizers.Adagrad(lr=0.1))
history = model.fit(x, y,
batch_size=150, epochs=1000,
verbose=1)

# here it should go test data
loss = model.evaluate(x, y, verbose=1)
print("\nMSE loss:", loss)

# Measure RMSE error.  RMSE is common for regression. here we use sklearn.metrics
# but above, by default keras uses MSE for regression, so we only need to take np.sqrt()
pred = list(model.predict(x))
score = np.sqrt(metrics.mean_squared_error(pred,y))
print("Final score (RMSE): {} and from the model {}".format(score,np.sqrt(loss)))

# How to make many predictions
# make sure to convert to float (dtype=float) and put it in two brakets so the shape is correct
sample = np.array([[1.496308,1.089233,0.672271,0.630077,-1.293870,70.,1.,0.,0.]], dtype=float)
pred = list(model.predict(sample))
predDF = pd.DataFrame(pred)
df2 = pd.concat([df,predDF,pd.DataFrame(y)],axis=1)

df2.columns = list(df.columns)+['pred','ideal']
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
mpg             398 non-null float64
cylinders       398 non-null int64
displacement    398 non-null float64
horsepower      392 non-null float64
weight          398 non-null int64
acceleration    398 non-null float64
year            398 non-null int64
origin          398 non-null int64
name            398 non-null object
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB
None
              mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   


398/398 [==============================] - 0s - loss: 12.3927     
Epoch 68/1000
398/398 [==============================] - 0s - loss: 13.1230     
Epoch 69/1000
398/398 [==============================] - 0s - loss: 12.3110     
Epoch 70/1000
398/398 [==============================] - 0s - loss: 12.5390     
Epoch 71/1000
398/398 [==============================] - 0s - loss: 12.9525     
Epoch 72/1000
398/398 [==============================] - 0s - loss: 13.3096     
Epoch 73/1000
398/398 [==============================] - 0s - loss: 12.2702     
Epoch 74/1000
398/398 [==============================] - 0s - loss: 12.8250     
Epoch 75/1000
398/398 [==============================] - 0s - loss: 12.4744     
Epoch 76/1000
398/398 [==============================] - 0s - loss: 12.2585     
Epoch 77/1000
398/398 [==============================] - 0s - loss: 12.0983     
Epoch 78/1000
398/398 [==============================] - 0s - loss: 12.0372     
Epoch 79/1000
398/398 [===================

398/398 [==============================] - 0s - loss: 11.5847     
Epoch 168/1000
398/398 [==============================] - 0s - loss: 11.0863     
Epoch 169/1000
398/398 [==============================] - 0s - loss: 11.1229    
Epoch 170/1000
398/398 [==============================] - 0s - loss: 11.1334     
Epoch 171/1000
398/398 [==============================] - 0s - loss: 11.1427     
Epoch 172/1000
398/398 [==============================] - 0s - loss: 11.2043     
Epoch 173/1000
398/398 [==============================] - 0s - loss: 11.2722    
Epoch 174/1000
398/398 [==============================] - 0s - loss: 11.4463    
Epoch 175/1000
398/398 [==============================] - 0s - loss: 11.3940     
Epoch 176/1000
398/398 [==============================] - 0s - loss: 11.3140     
Epoch 177/1000
398/398 [==============================] - 0s - loss: 11.3109     
Epoch 178/1000
398/398 [==============================] - 0s - loss: 11.2131     
Epoch 179/1000
398/398 [==========

398/398 [==============================] - 0s - loss: 11.2244     
Epoch 267/1000
398/398 [==============================] - 0s - loss: 10.9655     
Epoch 268/1000
398/398 [==============================] - 0s - loss: 10.9860     
Epoch 269/1000
398/398 [==============================] - 0s - loss: 10.9292     
Epoch 270/1000
398/398 [==============================] - 0s - loss: 11.0784     
Epoch 271/1000
398/398 [==============================] - 0s - loss: 11.0155     
Epoch 272/1000
398/398 [==============================] - 0s - loss: 11.0815     
Epoch 273/1000
398/398 [==============================] - 0s - loss: 11.0837    
Epoch 274/1000
398/398 [==============================] - 0s - loss: 10.9123     
Epoch 275/1000
398/398 [==============================] - 0s - loss: 11.2819    
Epoch 276/1000
398/398 [==============================] - 0s - loss: 10.9596     
Epoch 277/1000
398/398 [==============================] - 0s - loss: 11.1792    
Epoch 278/1000
398/398 [==========

398/398 [==============================] - 0s - loss: 10.9167     
Epoch 367/1000
398/398 [==============================] - 0s - loss: 10.7981     
Epoch 368/1000
398/398 [==============================] - 0s - loss: 10.8180     
Epoch 369/1000
398/398 [==============================] - 0s - loss: 10.7826    
Epoch 370/1000
398/398 [==============================] - 0s - loss: 10.8078     
Epoch 371/1000
398/398 [==============================] - 0s - loss: 10.8187     
Epoch 372/1000
398/398 [==============================] - 0s - loss: 11.3640     
Epoch 373/1000
398/398 [==============================] - 0s - loss: 10.7694     
Epoch 374/1000
398/398 [==============================] - 0s - loss: 10.7700     
Epoch 375/1000
398/398 [==============================] - 0s - loss: 11.1077    
Epoch 376/1000
398/398 [==============================] - 0s - loss: 10.7744     
Epoch 377/1000
398/398 [==============================] - 0s - loss: 10.8509     
Epoch 378/1000
398/398 [=========

398/398 [==============================] - 0s - loss: 10.7215    
Epoch 467/1000
398/398 [==============================] - 0s - loss: 10.8265     
Epoch 468/1000
398/398 [==============================] - 0s - loss: 10.6419    
Epoch 469/1000
398/398 [==============================] - 0s - loss: 10.7828     
Epoch 470/1000
398/398 [==============================] - 0s - loss: 10.7334     
Epoch 471/1000
398/398 [==============================] - 0s - loss: 10.6448     
Epoch 472/1000
398/398 [==============================] - 0s - loss: 10.6543    
Epoch 473/1000
398/398 [==============================] - 0s - loss: 10.6997    
Epoch 474/1000
398/398 [==============================] - 0s - loss: 10.8071     
Epoch 475/1000
398/398 [==============================] - 0s - loss: 10.8382     
Epoch 476/1000
398/398 [==============================] - 0s - loss: 10.8112     
Epoch 477/1000
398/398 [==============================] - 0s - loss: 11.0457     
Epoch 478/1000
398/398 [===========

398/398 [==============================] - 0s - loss: 10.5706     
Epoch 567/1000
398/398 [==============================] - 0s - loss: 10.5784     
Epoch 568/1000
398/398 [==============================] - 0s - loss: 10.6368     
Epoch 569/1000
398/398 [==============================] - 0s - loss: 10.5189    
Epoch 570/1000
398/398 [==============================] - 0s - loss: 10.5962    
Epoch 571/1000
398/398 [==============================] - 0s - loss: 10.7638    
Epoch 572/1000
398/398 [==============================] - 0s - loss: 10.5952    
Epoch 573/1000
398/398 [==============================] - 0s - loss: 10.5492     
Epoch 574/1000
398/398 [==============================] - 0s - loss: 10.5306     
Epoch 575/1000
398/398 [==============================] - 0s - loss: 10.9349    
Epoch 576/1000
398/398 [==============================] - 0s - loss: 10.8269     
Epoch 577/1000
398/398 [==============================] - 0s - loss: 10.7573     
Epoch 578/1000
398/398 [============

398/398 [==============================] - 0s - loss: 10.4079     
Epoch 666/1000
398/398 [==============================] - 0s - loss: 10.4452     
Epoch 667/1000
398/398 [==============================] - 0s - loss: 10.3834     
Epoch 668/1000
398/398 [==============================] - 0s - loss: 10.4706     
Epoch 669/1000
398/398 [==============================] - 0s - loss: 11.1459     
Epoch 670/1000
398/398 [==============================] - 0s - loss: 10.5254     
Epoch 671/1000
398/398 [==============================] - 0s - loss: 10.4493     
Epoch 672/1000
398/398 [==============================] - 0s - loss: 10.5838    
Epoch 673/1000
398/398 [==============================] - 0s - loss: 10.3962     
Epoch 674/1000
398/398 [==============================] - 0s - loss: 10.4324     
Epoch 675/1000
398/398 [==============================] - 0s - loss: 10.4284     
Epoch 676/1000
398/398 [==============================] - 0s - loss: 10.4235     
Epoch 677/1000
398/398 [========

398/398 [==============================] - 0s - loss: 10.5138     
Epoch 765/1000
398/398 [==============================] - 0s - loss: 11.9295     
Epoch 766/1000
398/398 [==============================] - 0s - loss: 10.5658     
Epoch 767/1000
398/398 [==============================] - 0s - loss: 10.4166     
Epoch 768/1000
398/398 [==============================] - 0s - loss: 10.3577    
Epoch 769/1000
398/398 [==============================] - 0s - loss: 10.4079     
Epoch 770/1000
398/398 [==============================] - 0s - loss: 10.4093     
Epoch 771/1000
398/398 [==============================] - 0s - loss: 10.2975     
Epoch 772/1000
398/398 [==============================] - 0s - loss: 10.5430     
Epoch 773/1000
398/398 [==============================] - 0s - loss: 10.2834    
Epoch 774/1000
398/398 [==============================] - 0s - loss: 10.2528    
Epoch 775/1000
398/398 [==============================] - 0s - loss: 10.2825     
Epoch 776/1000
398/398 [==========

398/398 [==============================] - 0s - loss: 10.1739     
Epoch 865/1000
398/398 [==============================] - 0s - loss: 10.1480     
Epoch 866/1000
398/398 [==============================] - 0s - loss: 10.2823    
Epoch 867/1000
398/398 [==============================] - 0s - loss: 10.3289     
Epoch 868/1000
398/398 [==============================] - 0s - loss: 10.2669     
Epoch 869/1000
398/398 [==============================] - 0s - loss: 10.1695     
Epoch 870/1000
398/398 [==============================] - 0s - loss: 10.1615     
Epoch 871/1000
398/398 [==============================] - 0s - loss: 10.1411     
Epoch 872/1000
398/398 [==============================] - 0s - loss: 10.2050     
Epoch 873/1000
398/398 [==============================] - 0s - loss: 10.1998     
Epoch 874/1000
398/398 [==============================] - 0s - loss: 10.1780     
Epoch 875/1000
398/398 [==============================] - 0s - loss: 10.2227     
Epoch 876/1000
398/398 [========

398/398 [==============================] - 0s - loss: 10.1001     
Epoch 965/1000
398/398 [==============================] - 0s - loss: 10.3422    
Epoch 966/1000
398/398 [==============================] - 0s - loss: 10.1308     
Epoch 967/1000
398/398 [==============================] - 0s - loss: 10.1136     
Epoch 968/1000
398/398 [==============================] - 0s - loss: 10.2534    
Epoch 969/1000
398/398 [==============================] - 0s - loss: 10.0907    
Epoch 970/1000
398/398 [==============================] - 0s - loss: 10.2351     
Epoch 971/1000
398/398 [==============================] - 0s - loss: 10.1090    
Epoch 972/1000
398/398 [==============================] - 0s - loss: 10.0538    
Epoch 973/1000
398/398 [==============================] - 0s - loss: 10.0845    
Epoch 974/1000
398/398 [==============================] - 0s - loss: 10.1826    
Epoch 975/1000
398/398 [==============================] - 0s - loss: 10.0501     
Epoch 976/1000
398/398 [==============

mpg  cylinders  displacement  horsepower    weight  acceleration  year  \
0  18.0   1.496308      1.089233    0.672271  0.630077     -1.293870    70   
1  15.0   1.496308      1.501624    1.587959  0.853259     -1.475181    70   
2  18.0   1.496308      1.194728    1.195522  0.549778     -1.656492    70   
3  16.0   1.496308      1.060461    1.195522  0.546236     -1.293870    70   
4  17.0   1.496308      1.041280    0.933897  0.565130     -1.837804    70   

   origin-1  origin-2  origin-3     pred  ideal  
0         1         0         0  15.7096   18.0  
1         1         0         0      NaN   15.0  
2         1         0         0      NaN   18.0  
3         1         0         0      NaN   16.0  
4         1         0         0      NaN   17.0

### The same as above but with train/test split and Early Stopping

In [302]:
import tensorflow.contrib.keras as keras # tensorflow version for this case is v1.1
# from tensorflow.contrib.keras.layers import Input
import pandas as pd
import os
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from scipy.stats import zscore

path = "./data/"

filename_read = os.path.join(path,"auto-mpg.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])

print(df.info())
print(df.describe())


# create feature vector
missing_median(df, 'horsepower')
df.drop('name',1,inplace=True)
encode_numeric_zscore(df, 'horsepower')
encode_numeric_zscore(df, 'weight')
encode_numeric_zscore(df, 'cylinders')
encode_numeric_zscore(df, 'displacement')
encode_numeric_zscore(df, 'acceleration')
encode_text_dummy(df, 'origin')


# Display training data
df

# Encode to a 2D matrix for training
x,y = to_xy(df,'mpg')

# splitting the data into train and test 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

# Get/clear a directory to store the neural network to
model_dir = get_model_dir('mpg',True)

# Create a deep neural network with 3 hidden layers of 50, 25, 10

## this way is how the book "deep learning with keras" describes
# features = keras.layers.Input(shape=(9,))
# nn = keras.layers.Dense(50, activation="relu", kernel_initializer="glorot_uniform")(features)
# nn = keras.layers.Dense(25, activation="relu", kernel_initializer="glorot_uniform")(nn)
# nn = keras.layers.Dense(10, activation="relu", kernel_initializer="glorot_uniform")(nn)
# mpg = keras.layers.Dense(1, kernel_initializer="glorot_uniform")(nn)

# model = keras.models.Model(inputs=[features], outputs=[mpg])
# model.compile(loss="mse", optimizer="adam")

# # train network
# NUM_EPOCHS = 1000
# BATCH_SIZE = 64

# history = model.fit(x, y, batch_size=BATCH_SIZE, epochs=NUM_EPOCHS)


## this was is how I've seen model being constructed in other examples - for now I prefer this one

model = keras.models.Sequential()
model.add(keras.layers.Dense(50, input_dim=x_train.shape[1], kernel_initializer="glorot_uniform"))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dense(25, kernel_initializer="glorot_uniform"))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dense(10, kernel_initializer="glorot_uniform"))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dense(1))
model.summary()
model.compile(loss='mse',
                optimizer=keras.optimizers.Adagrad(lr=0.1))
# history = model.fit(x_train, y_train,
# batch_size=150, epochs=1000,
# verbose=1)


earlyStopping = keras.callbacks.EarlyStopping(monitor='val_loss' ,patience=4, verbose=1, mode='auto')

model.fit(x_train, y_train, batch_size=150, epochs=10000, verbose=2, \
          callbacks=[earlyStopping], validation_data=(x_test, y_test))



# here it should go test data
loss = model.evaluate(x_test, y_test, verbose=1)
print("\nMSE validation loss:", loss)

# Measure RMSE error.  RMSE is common for regression. here we use sklearn.metrics
# but above, by default keras uses MSE for regression, so we only need to take np.sqrt()
pred = list(model.predict(x_test))
score = np.sqrt(metrics.mean_squared_error(pred,y_test))
print("Final score (RMSE): {}".format(score))

# How to make many predictions
# make sure to convert to float (dtype=float) and put it in two brakets so the shape is correct
sample = np.array([[1.496308,1.089233,0.672271,0.630077,-1.293870,70.,1.,0.,0.]], dtype=float)
pred = list(model.predict(sample))
predDF = pd.DataFrame(pred)
df2 = pd.concat([df,predDF,pd.DataFrame(y)],axis=1)

df2.columns = list(df.columns)+['pred','ideal']
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
mpg             398 non-null float64
cylinders       398 non-null int64
displacement    398 non-null float64
horsepower      392 non-null float64
weight          398 non-null int64
acceleration    398 non-null float64
year            398 non-null int64
origin          398 non-null int64
name            398 non-null object
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB
None
              mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   


mpg  cylinders  displacement  horsepower    weight  acceleration  year  \
0  18.0   1.496308      1.089233    0.672271  0.630077     -1.293870    70   
1  15.0   1.496308      1.501624    1.587959  0.853259     -1.475181    70   
2  18.0   1.496308      1.194728    1.195522  0.549778     -1.656492    70   
3  16.0   1.496308      1.060461    1.195522  0.546236     -1.293870    70   
4  17.0   1.496308      1.041280    0.933897  0.565130     -1.837804    70   

   origin-1  origin-2  origin-3       pred  ideal  
0         1         0         0  14.950416   18.0  
1         1         0         0        NaN   15.0  
2         1         0         0        NaN   18.0  
3         1         0         0        NaN   16.0  
4         1         0         0        NaN   17.0

In [279]:
x[0]

# sample = np.array([1.496308,1.089233,0.672271,0.630077,-1.293870,70.,1.,0.,0.], dtype=float)

array([  1.49630797,   1.08923268,   0.67227149,   0.63007683,
        -1.29386985,  70.        ,   1.        ,   0.        ,   0.        ], dtype=float32)

# Load/Save Trained Network

When the neural network is created we must specify a directory that the neural network is saved to.  Often we clear out that directory so that training can start over.  This clearing is accomplished by calling the **get_model_dir** method with the second paramater of True.  The code below trains an iris neural network, exactly as before.

In [47]:
import tensorflow as tf
import tensorflow.contrib.learn as learn
from sklearn import metrics
import pandas as pd
import os
from sklearn import preprocessing

path = "./data/"

# Read iris dataset
filename_read = os.path.join(path,"iris.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])

# Extract just the columns we shall predict on
encode_numeric_zscore(df,'sepal_l')
encode_numeric_zscore(df,'sepal_w')
encode_numeric_zscore(df,'petal_l')
encode_numeric_zscore(df,'petal_w')
species = encode_text_index(df,'species')
num_classes = len(species)

# Create x(predictors) and y (expected outcome)
x,y = to_xy(df,'species')

# Get/clear a directory to store the neural network to
model_dir = get_model_dir('iris',True)

# Create a deep neural network with 3 hidden layers of 10, 20, 5
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=x.shape[1])]
classifier = learn.DNNClassifier(
    model_dir= model_dir,
    hidden_units=[10, 20, 5], n_classes=num_classes, feature_columns=feature_columns)

# Might be needed in future versions of "TensorFlow Learn"
#classifier = learn.SKCompat(classifier) # For Sklearn compatibility

# Fit/train neural network
classifier.fit(x, y, steps=1000)

# Measure accuracy
pred = list(classifier.predict(x, as_iterable=True))
score = metrics.accuracy_score(y, pred)
print("Accuarcy before save: {}".format(score))

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_tf_random_seed': None, '_master': '', '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_num_worker_replicas': 0, '_save_checkpoints_steps': None, '_is_chief': True, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f10587f1a20>, '_model_dir': None, '_save_summary_steps': 100, '_environment': 'local', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_evaluation_master': '', '_task_id': 0, '_keep_checkpoint_every_n_hours': 10000}
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving 

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py:248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  equality = a == b


INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into ./dnn/iris/model.ckpt.
INFO:tensorflow:step = 1, loss = 1.1572
INFO:tensorflow:global_step/sec: 836.09
INFO:tensorflow:step = 101, loss = 0.108447 (0.120 sec)
INFO:tensorflow:global_step/sec: 1023.95
INFO:tensorflow:step = 201, loss = 0.0498121 (0.098 sec)
INFO:tensorflow:global_step/sec: 988.146
INFO:tensorflow:step = 301, loss = 0.0351476 (0.100 sec)
INFO:tensorflow:global_step/sec: 928.309
INFO:tensorflow:step = 401, loss = 0.0286369 (0.108 sec)
INFO:tensorflow:global_step/sec: 997.07
INFO:tensorflow:step = 501, loss = 0.0241446 (0.100 sec)
INFO:tensorflow:global_step/sec: 990.384
INFO:tensorflow:step = 601, loss = 0.0203176 (0.101 sec)
INFO:tensorflow:global_step/sec: 980.142
INFO:tensorflow:step = 701, loss = 0.0167216 (0.102 sec)
INFO:tensorflow:global_step/sec: 994.05
INFO:tensorflow:step = 801, loss = 0.0133563 (0.100 sec)
INFO:tensorflow:global_step/sec: 985.956
INFO:tensorflow:step = 901

The code below sets up a neural network and reads the data (for predictions), but it does not clear the model directory or fit the neural network.  The weights from the previous fit are used.

In [44]:
import tensorflow as tf
import tensorflow.contrib.learn as learn
from sklearn import metrics
import pandas as pd
import os
from sklearn import preprocessing

path = "./data/"

# Read iris dataset
filename_read = os.path.join(path,"iris.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])

# Extract just the columns we shall predict on
encode_numeric_zscore(df,'sepal_l')
encode_numeric_zscore(df,'sepal_w')
encode_numeric_zscore(df,'petal_l')
encode_numeric_zscore(df,'petal_w')
species = encode_text_index(df,'species')
num_classes = len(species)

# Create x(predictors) and y (expected outcome)
x,y = to_xy(df,'species')

# Get/clear a directory to store the neural network to
model_dir = get_model_dir('iris',False)  # False, do not clear!!! Use saved network.

# Create a deep neural network with 3 hidden layers of 10, 20, 5
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=x.shape[1])]
classifier = learn.DNNClassifier(
    model_dir= model_dir,
    hidden_units=[10, 20, 5], n_classes=num_classes, feature_columns=feature_columns)

# Do not fit!!!!!!!!!!!!!!!!!!!!

# Measure accuracy
pred = list(classifier.predict(x, as_iterable=True))
score = metrics.accuracy_score(y, pred)
print("Accuarcy after load: {}".format(score))

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_tf_random_seed': None, '_master': '', '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_num_worker_replicas': 0, '_save_checkpoints_steps': None, '_is_chief': True, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1058b8c860>, '_model_dir': None, '_save_summary_steps': 100, '_environment': 'local', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_evaluation_master': '', '_task_id': 0, '_keep_checkpoint_every_n_hours': 10000}
Instructions for updating:
Please switch to predict_classes, or set `outputs` argument.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))


/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py:248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  equality = a == b


INFO:tensorflow:Restoring parameters from ./dnn/iris/model.ckpt-1000
Accuarcy after load: 1.0


# View Graph for Neural Network

TensorFlow includes the command line utility called [**tensorboard**](https://www.tensorflow.org/versions/r0.10/how_tos/summaries_and_tensorboard/index.html) that can be used to visualize the neural networks.  It is not needed for this course, but it can be handy to see your neural network, and I will use it in lecture a few times.  It does not work with IBM Data Scientist Workbench, so you will need a native install if you would like to use it.

To make use of it, you must specify a **logdir** on the fit command, for example:

```
classifier.fit(x, y, logdir='./log/')
```

Once the **fit** occurs, the logdir will be filled with files that **tensorboard** will use.  To view the graph, issue the following command:

```
tensorboard --logdir ./log
```

**my edit**
In order to use it with tensorflow v1.1 just type the command below in the command line
```
tensorboard --logdir=/home/yol/Documents/Dev/jh_dl/dnn
```
(full path to the log files)